### PR TITLE
Provide base for 2.15

### PR DESCRIPTION
**Pull request by CoRfr**
Version 2.15 of Gerrit is coming:
https://www.gerritcodereview.com/releases/2.15.md

Highlights:
- New change workflows for changes not yet ready for full review
  (formerly Drafts).
- The new PolyGerrit UI is mature enough for most uses.
- Account data is stored in NoteDb.
- NoteDb migration for change metadata is available.
- Made several improvements and additions to the documentation to
  help
  users find the information they need.

Change-Id: I767b84f078552ceb81fb3772fb4091227abf9d66

### CODE REVIEW

**Comment by CoRfr** [comment]
This is not meant for master but for a new branch 2.15-rcx !
Couldn't figure out a way to propose a new branch as a pull request.

**Comment by thinkernel** [comment]
A 2.15.rc branch is created. Would you please rebase you commit then submit your PR on that branch again? However, I kind of feel that it's a little early for us to track the 2.15 already, unless you really need to see how it works on docker.

**Comment by CoRfr** [comment]
I'm starting to experiment with 2.15 as I'm working on a new infrastructure and would like to try a database free design. Seems like NoteDb might be ready for prime time.

However I already have a branch in my fork so it won't impact me if you don't accept this PR, and it is more an open question about whether or not we want to make some pre releases available in a separate branch. I imagine that we could remove that branch once 2.15 is out.

I'm also wondering about the interest for a 'nightly' branch that would just take the latest Gerrit and plugins out of CI.

**Comment by thinkernel** [comment]
Someone just asked me a question in #77 about the NoteDB that makes me notice the database free option introduced in 2.15. It's so tempting and I even want to have a look at it myself. So I think it's worth creating a temporary RC branch for it. 

Nightly branch is also open to discuss. Although I have to figure out a way to trigger it nightly.

**Pull request merged**
