### PR TITLE
bump gerrit to 2.12.3

### PR DESCRIPTION
**Pull request by wingyplus**
Hi

I upgrade gerrit to the latest version (2.12.3). please review it.

Thanks

### CODE REVIEW

**Comment by ssaavedra** [comment]
You might also want to change the README if this pull request finally lands, so that users are aware that it is an up-to-date version.

**Comment by thinkernel** [comment]
@wingyplus Thanks for the patch.
@ssaavedra Thanks for the hint. I'll update the README.

**Comment by thinkernel** [comment]
Merged.

**Comment by wingyplus** [comment]
Thanks @ssaavedra  @thinkernel

**Pull request closed without merging**
