### PR TITLE
Adds init arguments that are used only on upgrade

### PR DESCRIPTION
**Pull request by brvollino**
There was a 'directory not found' problem when installing
plugins on initialization using '--install-plugin'.

Installing them only on the second initialization (upgrade) fixes it.

### CODE REVIEW

**Comment by brvollino** [comment]
Maybe it would be better to use "--skip-plugins" on first initialization. I will give it a try.

**Comment by thinkernel** [comment]
Hi there.
I use `--install-plugin=download-commands` as part of `GERRIT_INIT_ARGS` in my installation. There isn't 'directory not found' in the logs.  I have a [demo compose project](https://github.com/openfrontier/ci-compose/blob/master/docker-compose.yml#L50) which shows how to use some docker images to compose a CI system. This gerrit image is extended and used as a part of it. I run this demo again by using the latest image and can't find any 'directory not found' error in the logs. I will show you part of the logs later. 
There were some guys who reported similar issues. Most of them mounted a local directory as a volume into the container and that is not a recommend way because directories in the host may have different owner than the one into the container. 
Anyway, if you could show me your docker command line and the echo of `docker logs`, it might be easier for me to figure out the problem of this issue.

**Comment by thinkernel** [comment]
Here is a part of the gerrit start logs on my host.
> Attaching to cicompose_gerrit_1
> gerrit_1         |
> gerrit_1         | /gerrit-entrypoint.sh: running /docker-entrypoint-init.d/gerrit-init.nohup
> gerrit_1         |
> gerrit_1         | Initializing Gerrit...
> gerrit_1         | Testing Gerrit Connection
> gerrit_1         | Gerrit unavailable, sleeping for 10

There isn't any error log between initialize and upgrade.

> gerrit_1         | Upgrading gerrit...
> gerrit_1         | Initialized /var/gerrit/review_site
> gerrit_1         | Reindexing...
> gerrit_1         | Gerrit unavailable, sleeping for 10
> gerrit_1         | [2016-12-27 06:21:18,475] [main] INFO  com.google.gerrit.server.git.LocalDiskRepositoryManager : Defaulting core.streamFileThreshold to 220m
> gerrit_1         | [2016-12-27 06:21:21,142] [main] INFO  com.google.gerrit.server.cache.h2.H2CacheFactory : Enabling disk cache /var/gerrit/review_site/cache
> gerrit_1         | Gerrit unavailable, sleeping for 10
> Reindexing accounts:    100% (2/2)
> gerrit_1         | Reindexed 2 documents in accounts index in 1.7s (1.2/s)
> Collecting projects:    4
> Reindexing changes: projects: 100% (4/4), done
> gerrit_1         | Reindexed 0 documents in changes index in 0.2s (0.0/s)
> gerrit_1         | Upgrading is OK.
> gerrit_1         | Starting Gerrit...
> gerrit_1         | ulimit: unrecognized option: x
> gerrit_1         | Running Gerrit Code Review:

**Comment by brvollino** [comment]
The problem was that I believed I could add any plugin listed on gerrit's docs just by passing --install-plugin arguments through GERRIT_INIT_ARGS env parameter.

I've just realized that to install them I have to download the jars, so I did it in my Dockerfile and added them  them to $GERRIT_SITE/plugins/ using a script in docker-entrypoint-init.d.

I've found it a bit cumbersome, but it works. If there is any simpler way to do that, let me know, please

Thanks!

**Comment by thinkernel** [comment]
I think it might be the only way right now. As you can see that I also use this way to install some plugins like the plugin-events-log & gerrit-oauth-provider in the Dockerfile and the gerrit-entrypoint.sh. That's why the /docker-entrypoint-init.d is introduced into.

**Pull request closed without merging**
