### PR TITLE
Migrate image to alpine to save disk space

### PR DESCRIPTION
**Pull request by frostyslav**
I've modified image to use alpine instead of debian. It saves some disk space.
In comparison:
```
gerrit                     latest              785cc09f7c65        10 minutes ago      185.6 MB
openfrontier/gerrit        latest              7b6d1444837c        6 days ago          433.1 MB
```

### CODE REVIEW

**Comment by thinkernel** [comment]
Hi there.
I reviewed your work and I think it's pretty good. I really appreciate it.
Only one thing that I want to discuss with you. Would you mind adding the bash back?
As you may know that people can extend this image by adding some scripts under /docker-entrypoint-init.d. Those scripts may be written by bash. I'm afraid that removing bash by default may cause some inconveniences to other guys who has used bash.

**Comment by thinkernel** [comment]
I got an build error when I was trying to build the alpine version on both aws ami and centos. 

> + dpkg --print-architecture
> + wget -O /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/1.7/gosu-musl-linux-amd64
> Connecting to github.com (192.30.252.122:443)
> wget: server returned error: HTTP/1.1 404 Not Found

It seems that `dpkg --print-architecture` gives a `musl-linux-amd64` as the arch which is unavailable for the gosu distribution. Although I don't know what will happen when the build is triggered on the docker hub.

**Comment by thinkernel** [comment]
I modified `dpkg --print-architecture` to `amd64` in order to continue the building process. Then I got this one.

> Step 14 : RUN wget https://gerrit-releases.storage.googleapis.com/gerrit-${GERRIT_VERSION}.war -O $GERRIT_WAR
>  ---> Running in 22bdba362099
> Connecting to gerrit-releases.storage.googleapis.com (216.58.193.112:443)
> wget: can't execute 'ssl_helper': No such file or directory
> wget: error getting response: Connection reset by peer
> The command '/bin/sh -c wget https://gerrit-releases.storage.googleapis.com/gerrit-${GERRIT_VERSION}.war -O $GERRIT_WAR' returned a non-zero code: 1

I googled this message and found other reports about wget ssl on busybox is not working like [this one](https://github.com/gentoo/gentoo-docker-images/issues/29).
Do you know how to fix this? Advices would be appreciated.

**Comment by frostyslav** [comment]
Sorry, my bad. Totally forgot about the ca-certificates on centos.
Should work for centos now. However, I do not have access to amazon ami right now so I wasn't able to check it.
Size comparison right now:
```
gerrit                     latest              a940a08f46f5        4 minutes ago       188.2 MB
openfrontier/gerrit        latest              7b6d1444837c        6 days ago          433.1 MB
```

**Comment by thinkernel** [comment]
I can build the image successfully on AWS and docker hub. I created a container and it works perfectly. Great job. I actually learn a lot about how to migrate an docker image to alpine from your work. Thank you.

**Pull request merged**
